services:
  jupyterlab:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/notebooks
    entrypoint: >
      jupyter-lab
      --allow-root
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --NotebookApp.token=''
      --notebook-dir=/notebooks
    tty: true
    stdin_open: true